update dockerfile

diff --git a/frontend/Dockerfile.dev b/frontend/Dockerfile.dev
--- a/frontend/Dockerfile.dev
+++ b/frontend/Dockerfile.dev
@@ -1,20 +1,13 @@
-FROM node:20-alpine
+FROM node:20-alpine AS builder
+WORKDIR /app
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Add package file
-COPY package.json ./
-COPY yarn.lock ./
-
-# Install deps
-RUN yarn install
-
-# Copy source
-COPY src ./src
-COPY tsconfig.json ./tsconfig.json
-COPY tsconfig.node.json ./tsconfig.node.json
-
-# Build dist
-RUN yarn build
-
-EXPOSE 8080
+COPY . .
 
 CMD yarn run dev
